forge 'https://forge.puppet.com

mod 'puppetlabs-concat', :latest
mod 'puppetlabs-ruby_task_helper', :latest
mod 'puppetlabs-stdlib', :latest
mod 'puppetlabs-translate', :latest
mod 'WhatsARanjit-node_manager', :latest
mod 'puppetlabs-docker', :latest
mod 'puppet-hdm', :latest
mod 'puppet-hiera', :latest
mod 'puppetlabs-puppetserver_gem', :latest
mod 'puppetlabs-inifile', :latest